### ISSUE TITLE
The latest version problem on npm

### ISSUE THREAD

**Issue by nolsherry** [stripe/jquery.mobilePhoneNumber#12]
Hello @stripe,
I am the member of [cdnjs](https://github.com/cdnjs) project.
We want to host this library.
I  found the latest version is v1.0.7 on [github](https://github.com/stripe/jquery.mobilePhoneNumber), but the latest version on [npm](https://www.npmjs.com/package/jquery.mobilephonenumber) is v1.0.5. Could you update the latest version on npm?
Thanks very much!

cdnjs/cdnjs#8070

**Comment by jenanwise** [comment]
👍 Done!
